import React from "react";
import { AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig } from "remotion";
import { CorridorSweepSceneProps } from "../types";
import { colors, INTER, SAFE_ZONE } from "../styles";

export type { CorridorSweepSceneProps };

// ---------------------------------------------------------------------------
// Constants — fixed-frame timeline (spec'd for a 180-frame scene):
//   0–40    background dot grid fade in
//   40–90   corridor sweep reveal (clipPath translate)
//   90–130  in-corridor rides pop in, staggered every 6 frames, with a glow pulse
//   130–160 out-of-corridor rides fade in (dim)
//   160–180 corridor border pulse (0.3 → 0.6 → 0.3)
// ---------------------------------------------------------------------------
const VW = 1080;
const VH = 1920;
const CENTER = { x: VW / 2, y: VH / 2 };

const GRID_SPACING = 40;
const GRID_FADE_END = 40;

const SWEEP_START = 40;
const SWEEP_END = 90;

const INSIDE_START = 90;
const INSIDE_STAGGER = 6;
const INSIDE_ENTER_DURATION = 18;

const OUTSIDE_START = 130;
const OUTSIDE_END = 160;

const BORDER_PULSE_START = 160;
const BORDER_PULSE_MID = 170;
const BORDER_PULSE_END = 180;

const ACCENT_DEFAULT = "#00ff41";
const DOT_RADIUS = 5; // 10px diameter
const DOT_GLOW_BASE = 2;
const DOT_GLOW_PEAK = 6;

// Corridor's long axis is generated by rotating a horizontal strip so that
// its local x-axis (length) points mostly downward — this is what lets the
// sweep use a plain translateX from -length to 0 (per spec) while still
// reading as a top-left → bottom-right reveal.
const DIAGONAL = Math.hypot(VW, VH);
const CORRIDOR_LENGTH = DIAGONAL * 1.3; // overflows canvas at both ends regardless of angle
const LENGTH_SPREAD = VH * 0.55; // vertical range dots are generated across

// Deterministic PRNG (mulberry32) so dot placement never jitters on re-render.
function mulberry32(seed: number) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const clamp = (v: number, min: number, max: number) => Math.min(max, Math.max(min, v));

const glowStdDeviation = (frame: number, start: number, end: number) => {
  const t = interpolate(frame, [start, (start + end) / 2, end], [0, 1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  return DOT_GLOW_BASE + t * (DOT_GLOW_PEAK - DOT_GLOW_BASE);
};

export const CorridorSweepScene: React.FC<CorridorSweepSceneProps> = ({
  corridorAngleDeg = 20,
  corridorWidthPx = 280,
  rideCount = 8,
  outsideRideCount = 5,
  accentColor = ACCENT_DEFAULT,
  onScreenText,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const thetaRad = (corridorAngleDeg * Math.PI) / 180;
  const sinT = Math.sin(thetaRad);
  const cosT = Math.cos(thetaRad);
  const halfLength = CORRIDOR_LENGTH / 2;
  const halfWidth = corridorWidthPx / 2;

  // Local (px = along corridor length, py = across corridor width) ↔ world,
  // via the same rotation matrix used for the SVG group's rotate(90 - angle).
  const worldFromLocal = (px: number, py: number) => ({
    x: CENTER.x + px * sinT - py * cosT,
    y: CENTER.y + px * cosT + py * sinT,
  });

  // ---- Deterministic ride dots -------------------------------------------
  const rand = mulberry32(42);
  const insideDots = Array.from({ length: rideCount }, () => {
    const px = (rand() * 2 - 1) * LENGTH_SPREAD;
    const py = (rand() * 2 - 1) * Math.max(0, halfWidth - DOT_RADIUS - 12);
    const p = worldFromLocal(px, py);
    return { x: clamp(p.x, 50, VW - 50), y: clamp(p.y, 240, VH - 320) };
  });
  const outsideDots = Array.from({ length: outsideRideCount }, () => {
    const px = (rand() * 2 - 1) * LENGTH_SPREAD;
    const side = rand() < 0.5 ? -1 : 1;
    const py = side * (halfWidth + 30 + rand() * 160);
    const p = worldFromLocal(px, py);
    return { x: clamp(p.x, 50, VW - 50), y: clamp(p.y, 240, VH - 320) };
  });

  // ---- Animation values ---------------------------------------------------
  const gridOpacity = interpolate(frame, [0, GRID_FADE_END], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  const sweepTx = interpolate(frame, [SWEEP_START, SWEEP_END], [-CORRIDOR_LENGTH, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  const borderPulse = interpolate(
    frame,
    [BORDER_PULSE_START, BORDER_PULSE_MID, BORDER_PULSE_END],
    [0.3, 0.6, 0.3],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );

  const insideStart = (i: number) => INSIDE_START + i * INSIDE_STAGGER;

  return (
    <AbsoluteFill style={{ backgroundColor: colors.bg }}>
      <svg
        width="100%"
        height="100%"
        viewBox={`0 0 ${VW} ${VH}`}
        style={{ position: "absolute", top: 0, left: 0 }}
      >
        <defs>
          <pattern id="corridor-dot-grid" width={GRID_SPACING} height={GRID_SPACING} patternUnits="userSpaceOnUse">
            <circle cx={GRID_SPACING / 2} cy={GRID_SPACING / 2} r={1.5} fill="rgba(255,255,255,0.04)" />
          </pattern>
          <clipPath id="corridor-sweep-clip">
            <rect
              x={-halfLength - 40}
              y={-halfWidth - 40}
              width={CORRIDOR_LENGTH + 80}
              height={corridorWidthPx + 80}
              transform={`translate(${sweepTx}, 0)`}
            />
          </clipPath>
          {insideDots.map((_, i) => (
            <filter key={i} id={`corridor-glow-${i}`} x="-200%" y="-200%" width="500%" height="500%">
              <feGaussianBlur stdDeviation={glowStdDeviation(frame, insideStart(i), insideStart(i) + INSIDE_ENTER_DURATION)} result="blur" />
              <feMerge>
                <feMergeNode in="blur" />
                <feMergeNode in="SourceGraphic" />
              </feMerge>
            </filter>
          ))}
        </defs>

        {/* Background city-suggestive dot grid */}
        <rect width={VW} height={VH} fill="url(#corridor-dot-grid)" opacity={gridOpacity} />

        {/* Corridor: rotated strip whose local x-axis is the length axis, so
            the reveal below is a plain translateX from -length to 0 */}
        <g transform={`translate(${CENTER.x}, ${CENTER.y}) rotate(${90 - corridorAngleDeg})`}>
          <g clipPath="url(#corridor-sweep-clip)">
            <rect
              x={-halfLength}
              y={-halfWidth}
              width={CORRIDOR_LENGTH}
              height={corridorWidthPx}
              fill="rgba(0, 255, 65, 0.06)"
              stroke={accentColor}
              strokeOpacity={borderPulse}
              strokeWidth={1}
              strokeDasharray="6 6"
            />
          </g>
        </g>

        {/* Rides outside the corridor — dim, fade in after the in-corridor set */}
        {outsideDots.map((d, i) => {
          const opacity = interpolate(frame, [OUTSIDE_START, OUTSIDE_END], [0, 1], {
            extrapolateLeft: "clamp",
            extrapolateRight: "clamp",
          });
          if (opacity <= 0) return null;
          return (
            <circle key={i} cx={d.x} cy={d.y} r={DOT_RADIUS} fill="rgba(255,255,255,0.2)" opacity={opacity} />
          );
        })}

        {/* Rides inside the corridor — staggered pop-in with a glow pulse */}
        {insideDots.map((d, i) => {
          const start = insideStart(i);
          const scale = spring({
            frame: frame - start,
            fps,
            from: 0,
            to: 1,
            config: { stiffness: 260, damping: 16 },
            durationInFrames: INSIDE_ENTER_DURATION,
          });
          if (scale <= 0) return null;
          return (
            <g key={i} transform={`translate(${d.x}, ${d.y}) scale(${scale})`} filter={`url(#corridor-glow-${i})`}>
              <circle r={DOT_RADIUS} fill={accentColor} />
            </g>
          );
        })}
      </svg>

      {onScreenText && (
        <AbsoluteFill
          style={{
            justifyContent: "flex-end",
            alignItems: "center",
            paddingBottom: SAFE_ZONE.bottom,
            paddingLeft: SAFE_ZONE.left,
            paddingRight: SAFE_ZONE.right,
            pointerEvents: "none",
          }}
        >
          <span
            style={{
              fontSize: 20,
              fontWeight: 500,
              color: "rgba(255,255,255,0.6)",
              fontFamily: INTER,
              textAlign: "center",
            }}
          >
            {onScreenText}
          </span>
        </AbsoluteFill>
      )}
    </AbsoluteFill>
  );
};
